[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Boyu-Zhang-UOI/pml-f2026-notebooks/blob/main/02-data-science-stack/01_numpy_pandas_tutorial.ipynb)

# NumPy and Pandas for Machine Learning

This notebook introduces core NumPy array operations and Pandas DataFrame workflows commonly used in machine learning.

In [1]:
import numpy as np
import pandas as pd

np.set_printoptions(suppress=True)
pd.set_option('display.max_columns', 20)
pd.set_option('display.precision', 2)

## Array creation in NumPy

NumPy provides fast constructors for common patterns such as zeros, ones, ranges, and random samples.

In [2]:
rng = np.random.default_rng(42)

zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
sequence = np.arange(0, 12, 2)
grid = np.linspace(0, 1, 5)
random_values = rng.normal(loc=0.0, scale=1.0, size=(3, 3))

print('zeros:')
print(zeros)
print('ones:')
print(ones)
print('sequence:', sequence)
print('grid:', grid)
print('random_values:')
print(random_values)

zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
ones:
[[1. 1. 1.]
 [1. 1. 1.]]
sequence: [ 0  2  4  6  8 10]
grid: [0.   0.25 0.5  0.75 1.  ]
random_values:
[[ 0.30471708 -1.03998411  0.7504512 ]
 [ 0.94056472 -1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259 -0.01680116]]

## Indexing, slicing, and filtering

Slicing extracts structured subsets, while fancy indexing and boolean masks help us select specific rows or values.

In [3]:
X = np.arange(1, 13).reshape(3, 4)
print('X:')
print(X)
print('Second row:', X[1])
print('Last two columns:')
print(X[:, 2:])
print('Fancy row selection:')
print(X[[0, 2]])

mask = X % 2 == 0
print('Even entries:', X[mask])

X:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row: [5 6 7 8]
Last two columns:
[[ 3  4]
 [ 7  8]
 [11 12]]
Fancy row selection:
[[ 1  2  3  4]
 [ 9 10 11 12]]
Even entries: [ 2  4  6  8 10 12]

## Element-wise operations and broadcasting

NumPy applies arithmetic element-wise and can broadcast smaller arrays across larger ones.

In [4]:
scores = np.array([[78, 85, 90], [88, 79, 92], [95, 91, 87]])
bonus = np.array([2, 0, 3])

adjusted = scores + bonus
centered = scores - scores.mean(axis=0)
scaled = centered / scores.std(axis=0)

print('Adjusted scores:')
print(adjusted)
print('Centered scores:')
print(centered)
print('Scaled scores:')
print(scaled)

Adjusted scores:
[[80 85 93]
 [90 79 95]
 [97 91 90]]
Centered scores:
[[-9.          0.          0.33333333]
 [ 1.         -6.          2.33333333]
 [ 8.          6.         -2.66666667]]
Scaled scores:
[[-1.2901099   0.          0.16222142]
 [ 0.14334554 -1.22474487  1.13554995]
 [ 1.14676436  1.22474487 -1.29777137]]

## Reshaping and stacking

Reshaping reorganizes values without changing them. Stacking combines arrays into wider or taller structures.

In [5]:
flat = np.arange(12)
matrix = flat.reshape(3, 4)
column = np.array([100, 200, 300]).reshape(-1, 1)

print('Matrix:')
print(matrix)
print('Flattened:', matrix.ravel())
print('Column stack:')
print(np.hstack([matrix[:, :1], column]))
print('Vertical stack:')
print(np.vstack([matrix[:1], matrix[2:]]))

Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Column stack:
[[  0 100]
 [  4 200]
 [  8 300]]
Vertical stack:
[[ 0  1  2  3]
 [ 8  9 10 11]]

## Linear algebra tools

Many machine learning algorithms depend on matrix multiplication and decompositions.

In [6]:
A = np.array([[2.0, 1.0], [1.0, 3.0]])
B = np.array([[1.0, 4.0], [2.0, 5.0]])

print('dot:')
print(np.dot(A, B))
print('matmul:')
print(A @ B)
print('inverse of A:')
print(np.linalg.inv(A))
print('determinant of A:', np.linalg.det(A))
values, vectors = np.linalg.eig(A)
print('eigenvalues:', values)
print('eigenvectors:')
print(vectors)

dot:
[[ 4. 13.]
 [ 7. 19.]]
matmul:
[[ 4. 13.]
 [ 7. 19.]]
inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]
determinant of A: 5.000000000000001
eigenvalues: [1.38196601 3.61803399]
eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]

## Creating labeled data with Pandas

Pandas adds row and column labels, which makes tabular data easier to inspect and manipulate.

In [7]:
students = pd.Series([88, 93, 79], index=['Alice', 'Ben', 'Chloe'], name='quiz_score')

df = pd.DataFrame({
    'student': ['Alice', 'Ben', 'Chloe', 'Darius', 'Ella'],
    'study_hours': [6.5, 8.0, 4.0, 7.5, np.nan],
    'attendance': [0.95, 0.90, 0.80, 0.88, 0.92],
    'passed': [True, True, False, True, True]
})

print(students)
df

Alice    88
Ben      93
Chloe    79
Name: quiz_score, dtype: int64

  student  study_hours  attendance  passed
0   Alice          6.5        0.95    True
1     Ben          8.0        0.90    True
2   Chloe          4.0        0.80   False
3  Darius          7.5        0.88    True
4    Ella          NaN        0.92    True

In [8]:
print(df.loc[0:2, ['student', 'study_hours']])
print(df.iloc[:3, :2])
print(df[df['attendance'] >= 0.9])

  student  study_hours
0   Alice          6.5
1     Ben          8.0
2   Chloe          4.0
  student  study_hours
0   Alice          6.5
1     Ben          8.0
2   Chloe          4.0
  student  study_hours  attendance  passed
0   Alice          6.5        0.95    True
1     Ben          8.0        0.90    True
4    Ella          NaN        0.92    True

In [9]:
messy_df = pd.concat([df, df.iloc[[1]]], ignore_index=True)
messy_df.loc[4, 'study_hours'] = np.nan

cleaned_df = (
    messy_df
    .drop_duplicates()
    .assign(study_hours=lambda frame: frame['study_hours'].fillna(frame['study_hours'].median()))
)

print('Rows before cleaning:', len(messy_df))
print('Rows after cleaning:', len(cleaned_df))
cleaned_df

Rows before cleaning: 6
Rows after cleaning: 5

  student  study_hours  attendance  passed
0   Alice          6.5        0.95    True
1     Ben          8.0        0.90    True
2   Chloe          4.0        0.80   False
3  Darius          7.5        0.88    True
4    Ella          7.0        0.92    True

## Aggregation and joining

GroupBy summarizes data by category, and merges combine related tables from different sources.

In [10]:
summary = cleaned_df.groupby('passed').agg(
    avg_hours=('study_hours', 'mean'),
    avg_attendance=('attendance', 'mean'),
    count=('student', 'count')
)
summary

        avg_hours  avg_attendance  count
passed
False        4.00            0.80      1
True         7.25            0.91      4

In [11]:
advisor_df = pd.DataFrame({
    'student': ['Alice', 'Ben', 'Chloe', 'Darius', 'Ella'],
    'mentor': ['Dr. Lee', 'Dr. Lee', 'Dr. Kim', 'Dr. Kim', 'Dr. Singh']
})

merged = cleaned_df.merge(advisor_df, on='student', how='left')
merged

  student  study_hours  attendance  passed     mentor
0   Alice          6.5        0.95    True    Dr. Lee
1     Ben          8.0        0.90    True    Dr. Lee
2   Chloe          4.0        0.80   False    Dr. Kim
3  Darius          7.5        0.88    True    Dr. Kim
4    Ella          7.0        0.92    True  Dr. Singh

## Quick recap

You used NumPy for fast numerical operations and Pandas for labeled tabular analysis. These tools form the backbone of most machine learning preprocessing workflows.